-- Phase 9: Business Suggestions
-- Adds business_suggestions table and profile_version tracking

-- Add profile_version to user_business_profiles for cache invalidation
ALTER TABLE user_business_profiles
  ADD COLUMN IF NOT EXISTS profile_version INT NOT NULL DEFAULT 1;

-- Business suggestions generated by AI for course chapters
CREATE TABLE business_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  chapter_id UUID NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  business_potential TEXT NOT NULL,
  estimated_complexity TEXT NOT NULL CHECK (estimated_complexity IN ('prosty', 'sredni', 'zlozony')),
  relevant_section TEXT,
  model_name TEXT NOT NULL,
  input_hash TEXT NOT NULL,
  profile_version INT NOT NULL DEFAULT 1,
  is_bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
  is_dismissed BOOLEAN NOT NULL DEFAULT FALSE,
  dismissed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for daily limit check (user + date descending)
CREATE INDEX idx_business_suggestions_user_date
  ON business_suggestions (user_id, created_at DESC);

-- Index for chapter-level queries
CREATE INDEX idx_business_suggestions_user_chapter
  ON business_suggestions (user_id, chapter_id, created_at DESC);

-- RLS
ALTER TABLE business_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own suggestions"
  ON business_suggestions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own suggestions"
  ON business_suggestions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own suggestions"
  ON business_suggestions FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
